INSERT INTO `dbalucar`.`imagens`(`imagens_id`,`titulo`,`url_imagem`) 
VALUES 	(1, 'Onix','https://static.rentcars.com/imagens/carros/chevrolet_onix-2020-2021.png'), 
		(2, '208', 'https://static.rentcars.com/imagens/carros/peugeot_208-2020-2021.png'),
		(3, 'HB20','https://static.rentcars.com/imagens/carros/hyundai_hb20-2020-2021.png'),
		(4, 'Sandero','https://static.rentcars.com/imagens/carros/renault_sandero.png'),
		(5,'Logan', 'https://static.rentcars.com/imagens/carros/renault-logan-2021.png'), 
		(6,'Voyage','https://static.rentcars.com/imagens/carros/volkswagen_voyage-2020-2021.png'),
		(7,'Onix_Plus','https://static.rentcars.com/imagens/carros/chevrolet_onix_plus-2020-2021.png'),
		(8,'Versa','https://static.rentcars.com/imagens/carros/nissan-versa-2022.png'),
		(9,'UP','https://static.rentcars.com/imagens/carros/volkswagen_up-2020-2021.png'),
		(10,'MOBI','https://static.rentcars.com/imagens/carros/fiat_mobi-2020-2021.png'),
		(11,'Gol','https://static.rentcars.com/imagens/carros/volkswagen_gol-2020-2021.png'),
		(12,'KWID','https://static.rentcars.com/imagens/carros/renault_kwid-2020-2021.png'),
		(13,'2008','https://static.rentcars.com/imagens/carros/peugeot-2008.png'),
		(14,'Duster','https://static.rentcars.com/imagens/carros/renault_duster-2020-2021.png'),
		(15, 'Captur','https://static.rentcars.com/imagens/carros/renault-captur-2021.png'),
		(16,'T-Cross', 'https://static.rentcars.com/imagens/carros/vw_t-cross-2020-2021.png'),	
		(17,'Compass','https://static.rentcars.com/imagens/carros/jeep-compass.jpg'),
		(18, '3008', 'https://static.rentcars.com/imagens/carros/peugeot-3008-2021.png'),
		(19,'Tiguan 4x2','https://static.rentcars.com/imagens/carros/vw_tiguan.png');